name: blocpod_logger
description: Generic logging primitives for Blocpod.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
